# Summary

* [Introduction](README.md)

## GETTING STARTED

* [The Problem](getting-started/the-problem.md)
* [Quick Start](getting-started/quick-start.md)

## MARKET CONTEXT

* [Solana Prediction Markets](market-context/solana-markets.md)
* [The Oracle Challenge](market-context/oracle-challenge.md)

## PROTOCOL MECHANICS

* [System Overview](protocol-mechanics/system-overview.md)
* [Instant Settlement](protocol-mechanics/instant-settlement.md)
* [Parimutuel Pools](protocol-mechanics/parimutuel-pools.md)
* [Custom ROOMS Oracles](protocol-mechanics/oracle-integration.md)
* [Platform Fees](protocol-mechanics/platform-fees.md)
* [Referral System](protocol-mechanics/referral-system.md)
* [User Room Creation](protocol-mechanics/user-room-creation.md)

## HOW TO USE

* [Getting Started](how-to-use/getting-started.md)
* [Placing Bets](how-to-use/placing-bets.md)
* [Understanding Odds](how-to-use/understanding-odds.md)
* [Claiming Winnings](how-to-use/claiming-winnings.md)
* [Creating Rooms](how-to-use/creating-rooms.md)

## MARKET RULES

* [Market Guidelines](market-rules/market-guidelines.md)

## TECHNICAL

* [Architecture](technical/architecture.md)
* [Security](technical/security.md)
* [API Reference](technical/api-reference.md)

